erDiagram
    member ||--o{ revenue: pays
    member ||--|| contact: has_contact
    member }|--o{ borrow_request: creates
    book }|--o{ borrow_request: requested
    author }|--|{ book: writes
    publisher ||--|{ book: publishes

    member {
        string first_name
        string last_name
        date birthdate
        date registered
    }

    contact {
        string street
        string postal
        string email
        string phone
    }

    book {
        string title
        text synopsis
        string isbn
        int publisher_id
        date publication_date
        string genre
        string language
        int page_count
        string keywords
    }

    author {
        string first_name
        string last_name
        string country
        date birthdate
    }

    publisher {
        string name
        string website
        string email
        string phone
    }

    revenue {
        int member_id
        date date
        int amount
    }

    borrow_request {
        int book_id
        int member_id
        date borrow_date
        date due_date
        date complete_date
    }
